### ISSUE TITLE
Uique => Unique?

### ISSUE THREAD

**Issue by ArturBa** [AlenToma/expo-sqlite-wrapper#1]
Hi,

I've trying to use your package in my expo project.
Shouldn't it be _unique_ instead of _uique_ param?
https://github.com/AlenToma/expo-sqlite-wrapper/blob/main/src/TableStructor.ts#L21

**Comment by AlenToma** [comment]
yah, you are right will fix it and publish a new package sometimes later, thx

**Comment by AlenToma** [comment]
Fixed in version `1.2.0`
